const fs = require('fs');
let content = fs.readFileSync('/home/gustavo/.gemini/antigravity-cli/brain/150845b0-5ced-4323-ab5c-a2e2e3aaad73/.system_generated/steps/5/content.md', 'utf8');

// Find where HTML starts
const htmlStartIndex = content.indexOf('<!doctype html>');
if (htmlStartIndex !== -1) {
    let html = content.substring(htmlStartIndex);
    
    // Remove the line numbers that were injected by view_file or content.md if any
    // Wait, the content.md generated by read_url_content does NOT have line numbers. 
    // Line numbers are only added when view_file prints output.
    
    // String replacements for Guarani Telas
    html = html.replace(/Tigers Flooring/g, 'Guarani Telas');
    html = html.replace(/Tiger Flooring/g, 'Guarani Telas');
    html = html.replace(/Hardwood, Laminate &amp; Vinyl/g, 'Redes de Proteção &amp; Quadras Esportivas');
    html = html.replace(/Flooring/g, 'Telas e Quadras');
    html = html.replace(/Premium Flooring Solutions/g, 'Especialistas em Instalação');
    html = html.replace(/Schedule FREE At-Home Showroom/g, 'Orçamento via WhatsApp');
    html = html.replace(/352-329-6500/g, '47 3354-1338');
    html = html.replace(/352-875-2735/g, '47 99610-5585');
    
    // Inject Custom Colors and CSS overrides
    const cssOverride = `
    <style>
        /* Force text colors for Guarani */
        :root {
            --e-global-color-primary: #0014B4 !important;
            --e-global-color-secondary: #0014B4 !important;
            --e-global-color-text: #FFFFFF !important;
            --e-global-color-accent: #FFD100 !important;
        }
        
        .elementor-heading-title, .elementor-text-editor, .elementor-icon-list-text {
            color: #FFFFFF !important;
        }
        
        .th-accent, .th-accent-underline, .th-eyebrow .elementor-heading-title, .th-eyebrow-left .elementor-heading-title, .th-eyebrow-right .elementor-heading-title {
            color: #FFD100 !important;
        }
        
        .th-eyebrow .elementor-heading-title::before, .th-eyebrow .elementor-heading-title::after, .th-eyebrow-left .elementor-heading-title::before, .th-eyebrow-right .elementor-heading-title::after { 
            background: #FFD100 !important; 
        }
        
        .th-accent-underline::after { 
            background: linear-gradient(to right, #FFD100 0%, #FFD100 40%, rgba(255,209,0,0) 100%) !important; 
        }
        
        .dark-blob-bg {
            background-color: #000B66 !important;
            background-image:
                radial-gradient(ellipse 55% 45% at 12% 18%, rgba(0, 51, 204, 0.45), transparent 65%),
                radial-gradient(ellipse 50% 40% at 88% 30%, rgba(255, 209, 0, 0.12), transparent 65%),
                radial-gradient(ellipse 70% 55% at 50% 95%, rgba(0, 51, 204, 0.10), transparent 60%),
                radial-gradient(ellipse 45% 40% at 78% 75%, rgba(0, 11, 102, 0.40), transparent 60%),
                radial-gradient(ellipse 55% 50% at 22% 78%, rgba(0, 11, 102, 0.25), transparent 60%) !important;
        }
        
        /* Buttons */
        .elementor-button { 
            background-color: #FFD100 !important; 
            color: #000B66 !important; 
            border: none !important; 
            font-weight: 700 !important;
        }
        
        /* Swap Logo */
        .elementor-widget-image img[src*="Logo"] {
            content: url("/Logo-V1.png");
        }
    </style>
    `;
    
    html = html.replace('</head>', cssOverride + '</head>');
    
    fs.writeFileSync('index.html', html);
    console.log("Clone OK");
} else {
    console.log("HTML Start not found");
}
